language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: osx
      compiler: clang

addons:
  apt:
    packages:
      - libsqlite3-0
      - libsqlite3-dev
      - libgd3
      - libgd-dev
      - check

before_install:
 - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install gd sqlite check ; fi

script:
 - CFLAGS='-Wall -Wextra -g' ./configure && make check || ( cat test.log ; exit 1 ) && egrep '^[0-9]+%' test.log && ./vnstat --version

notifications:
  email:
    on_success: always
    on_failure: always
