git:
  depth: 10

language: c

matrix:
  include:
    - name: "Ubuntu 16.04 / GCC"
      os: linux
      dist: xenial
      compiler: gcc
      env:
        - CFLAGS='-Wall -Wextra'
        - CPARAMS='--enable-werror'
    - name: "Ubuntu 16.04 / Clang"
      os: linux
      dist: xenial
      compiler: clang
      env:
        - CFLAGS='-Weverything -Wno-padded'
        - CPARAMS='--enable-werror'
    - name: "Ubuntu 18.04 / GCC"
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - CFLAGS='-Wall -Wextra'
        - CPARAMS='--enable-werror'
    - name: "Ubuntu 18.04 / Clang"
      os: linux
      dist: bionic
      compiler: clang
      env:
        - CFLAGS='-Weverything -Wno-padded
        - CPARAMS='--enable-werror'
    - name: "Ubuntu 18.04 / Clang Sanitizers"
      os: linux
      dist: bionic
      compiler: clang
      env:
        - CFLAGS='-O1 -g -fsanitize=address -fno-omit-frame-pointer -fsanitize=undefined -fsanitize=nullability -fsanitize=implicit-conversion -fsanitize=integer'
        - CPARAMS='--enable-werror'
    - name: "OS X / Clang"
      os: osx
      osx_image: xcode11
      compiler: clang
      env:
        - CFLAGS='-Weverything -Wno-padded -Wno-reserved-id-macro -Wno-gnu-zero-variadic-macro-arguments -Wno-sign-conversion -Wno-unreachable-code -Wno-missing-noreturn'

addons:
  apt:
    packages:
      - libsqlite3-0
      - libsqlite3-dev
      - libgd3
      - libgd-dev
      - check
  homebrew:
    packages:
    - gd
    - sqlite
    - check

script:
 - ./configure ${CPARAMS} && make check || ( cat test.log ; cat test-suite.log ; exit 1 ) && ./vnstat --version && grep -iP 'sanitizer|runtime error' check_vnstat.log && exit 1 || true

notifications:
  email:
    on_success: always
    on_failure: always
