language: c

os:
 - linux
 - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo apt-get update -qq ; fi
 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo apt-get install -qq libsqlite3-0 libsqlite3-dev libgd2-xpm libgd2-xpm-dev check ; fi
 - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install gd sqlite check ; fi

script:
 - CFLAGS='-Wall -Wextra -g' ./configure && make check ; if [ "$?" -ne "0" ]; then egrep '^Running suite' -A1000 test-suite.log ; false ; else ./vnstat --version ; fi

notifications:
  email:
    on_success: always
    on_failure: always
