language: c

compiler:
  - gcc
  - clang

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libgd2-xpm libgd2-xpm-dev check

script: make debug && make tests && make install && vnstat --version

notifications:
  email:
    on_success: always
    on_failure: always
