git:
  depth: 10

language: c

matrix:
  include:
    - name: "Ubuntu 14.04 / GCC"
      os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env:
        - CFLAGS='-Wall -Wextra'
        - CPARAMS='--enable-werror'
    - name: "Ubuntu 14.04 / Clang"
      os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env:
        - CFLAGS='-Weverything -Wno-padded'
        - CPARAMS='--enable-werror'
    - name: "Ubuntu 16.04 / GCC"
      os: linux
      dist: xenial
      compiler: gcc
      env:
        - CFLAGS='-Wall -Wextra'
        - CPARAMS='--enable-werror'
    - name: "Ubuntu 16.04 / Clang"
      os: linux
      dist: xenial
      compiler: clang
      env:
        - CFLAGS='-Weverything -Wno-padded'
        - CPARAMS='--enable-werror'
    - name: "OS X / Clang"
      os: osx
      compiler: clang
      env:
        - CFLAGS='-Weverything -Wno-padded -Wno-reserved-id-macro -Wno-gnu-zero-variadic-macro-arguments -Wno-sign-conversion -Wno-unreachable-code -Wno-missing-noreturn'

addons:
  apt:
    packages:
      - libsqlite3-0
      - libsqlite3-dev
      - libgd3
      - libgd-dev
      - check

before_install:
 - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install gd sqlite check ; fi

script:
 - ./configure ${CPARAMS} && make check || ( cat test.log ; exit 1 ) && egrep '^[0-9]+%' test.log && CK_FORK=no ./check_vnstat || ( cat test.log ; exit 1 ) && ./vnstat --version

notifications:
  email:
    on_success: always
    on_failure: always
