language: c

os:
 - linux
 - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo apt-get update -qq ; fi
 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo apt-get install -qq libgd2-xpm libgd2-xpm-dev check ; fi
 - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install gd ; fi

script:
 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then ./configure && make debug && make check && src/vnstat --version ; fi
 - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then ./configure && make debug && src/vnstat --version ; fi

notifications:
  email:
    on_success: always
    on_failure: always
